### ISSUE TITLE
Inconsistent data being returned from /address/utxo/

### ISSUE THREAD

**Issue by alwaysAn0n** [bigearth/rest.bitbox.earth#18]
Hitting `https://rest.bitbox.earth/v1/address/utxo/` with a stringified array of cashaddress formatted addresses frequently yields different results.  This is true if you hit the server directly and also if you use the `Bitbox-cli` `BITBOX.Address.utxo()` method.  

If I remember correctly, this endpoint is relayed from Bitcoin.com .  If that's true, then the problem might actually be their Insight node.  Strangely enough, #17 looks like it might also be a problem with Bitcoin.com .  I've commented on that issue as well.

Here's a script that demonstrates my problem: https://gist.github.com/alwaysAn0n/433616933f2a0dbefe03c71650caa38a

EDIT: I tried hitting the endpoint one time for each address and it didn't fix the problem.  Same symptoms exactly.  I'm certain this is a problem with the Bitcoin.com Insight API library.

**Comment by cgcardona** [comment]
Has this been resolved w/ my recent change @alwaysAn0n ?

**Comment by alwaysAn0n** [comment]
Show nuff!  Thanks @cgcardona :)
